[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[colors.indexed_colors]]
color = "0xc9826b"
index = 16

[[colors.indexed_colors]]
color = "0xbf88bc"
index = 17

[colors.bright]
black = "0x465780"
blue = "0x8cafd2"
cyan = "0x93ccdc"
green = "0xb1d196"
magenta = "0xc895bf"
red = "0xd06f79"
white = "0xe7ecf4"
yellow = "0xf0d399"

[colors.cursor]
cursor = "#ECEFF4"
text = "#3B4252"

[colors.normal]
black = "0x3b4252"
blue = "0x81a1c1"
cyan = "0x88c0d0"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xe5e9f0"
yellow = "0xebcb8b"

[colors.primary]
background = "0x2e3440"
foreground = "0xcdcecf"

[cursor.style]
blinking = "Never"

[font]
normal = {family = "Hack Nerd Font", style = "Regular"}
bold = {family = "Hack Nerd Font", style = "Bold"}
italic = {family = "Hack Nerd Font", style = "Italic"}
size = 16.0
glyph_offset = { x = 0, y = 0 }
offset = {x = 0, y = 0}

[general]

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "Transparent"
opacity = 0.64
blur = true
padding = {x = 2, y = 2}
startup_mode = "SimpleFullscreen"

[keyboard]
