[shell]
program = "/usr/bin/zsh"

[window]
padding = {x = 2, y = 2}
decorations = "None"
opacity = 0.7
blur = true
startup_mode = "Maximized"

[scrolling]
history = 10000

[font]
normal = { family = "BigBlueTermPlus Nerd Font", style = "Regular"}
bold = { family = "BigBlueTermPlus Nerd Font", style = "Propo"}
italic = { family = "BigBlueTermPlus Nerd Font", style = "Mono"}
size = 13
glyph_offset = { x = 0, y = 0}

[colors.primary]
background = "0x2e3440"
foreground = "0xcdcecf"

[colors.normal]
black = "0x3b4252"
blue = "0x81a1c1"
cyan = "0x88c0d0"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xe5e9f0"
yellow = "0xebcb8b"

[colors.bright]
black = "0x465780"
blue = "0x8cafd2"
cyan = "0x93ccdc"
green = "0xb1d196"
magenta = "0xc895bf"
red = "0xd06f79"
white = "0xe7ecf4"
yellow = "0xf0d399"

[colors.cursor]
cursor = "#ECEFF4"
text = "#3B4252"

[[colors.indexed_colors]]
color = "0xc9826b"
index = 16

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[cursor.style]
blinking = "Never"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

