#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
# export PATH=$HOME/.cargo/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
eval "$(fnm env)"
export PYENV_ROOT="$HOME/.pyenv" 
export PATH="$PYENV_ROOT/bin:$PATH" 
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
# export PATH="$PATH:./node_modules/.bin"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/pbd0/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/pbd0/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/pbd0/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/pbd0/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# ROS Galactic
# source /opt/ros/galactic/setup.zsh
# export ROS_DOMAIN_ID=19
# source /usr/share/colcon_cd/function/colcon_cd.sh
# export _colcon_cd_root=/opt/ros/galactic/
# source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.zsh
# export LC_NUMERIC="en_US.UTF-8"
# eval "$(register-python-argcomplete3 ros2)"
# eval "$(register-python-argcomplete3 colcon)"

